### ISSUE TITLE
Value of PS1 variable not set and  the three .sh files don't have +x

### ISSUE THREAD

**Issue by GroceryBoyJr** [jimeh/git-aware-prompt#73]
When pulling the project, the git aware prompt doesn't work "out of the box". When I looked at the value of PS1, it wasn't getting assigned by the values from prompt.sh. Turns out PS1 wasn't being acted on by prompt.sh, so I uncommented the first PS1 example in the script comments at the bottom and it worked.

As a side note, the three .sh scripts don't have eXecute bits set.

They are also missing #!/bin/bash at the top, but they work OK without it.

**Comment by jimeh** [comment]
Right, yes out of the box it does nothing and instead leaves it up to the user to customize their prompt as they see fit. It simply provides tools for adding the git status to your prompt, rather than replace whatever your current prompt style is. The commented out PS1 examples are just that, examples for you to use if you want, or make your own.

Apologies if the instructions in the readme are not that clear about uneventful "out of the box" experience.

As for the script files, none of them actually need to be marked as executable or have a shebang, as they're not executed. They're sourced into a running bash instance.

I'll close this issue for now, but feel free to comment further if you have any more questions or feedback :)

**Comment by GroceryBoyJr** [comment]
Jim - you are awesome, thanks for  your extremely fast response!
There are other citations for your (very nice) work that also leave out the
definition of PS1.
May I please ask your permission to write another article on your work but
add one more step of defining PS1?
(I'd like to write it for enable-sysadmin.com, which is now known as
https://www.redhat.com/sysadmin/ )

James

**Comment by jimeh** [comment]
@GroceryBoyJr You're free to write any article you want about this project, or any of my projects really. And git-aware-prompt specifically is licensed under [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/), making public domain. So really you're free to do anything you like, without even asking for permission :)
